// 由 _l10n/gen_itemnames.py 生成，别手改。
// 数据来源：item_catalog.json（441 条，抄自游戏的本地化表）。
using System;
using System.Collections.Generic;

namespace DebugConsole
{
    /// <summary>
    /// 物品的英文显示名。中文名由游戏自己给，英文名游戏没现成接口，
    /// 所以在这儿放一张只读对照表；查不到就让调用方回落中文名。
    /// </summary>
    internal static class ItemNames
    {
        private static readonly Dictionary<string, string> Map =
            new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "100ml_cylinder", "100ml Graduated Cylinder" },
            { "1ml_dropper", "1ml Dropper" },
            { "25ml_cylinder", "25ml Graduated Cylinder" },
            { "3d_printer", "3D Printer" },
            { "3d_printer_instruction", "3D Printer Instruction" },
            { "50ml_cylinder", "50ml Graduated Cylinder" },
            { "5ml_dropper", "5ml Dropper" },
            { "advanced_flux_agent", "Flux Smelting Agent (Advanced)" },
            { "age_well", "AgeWell" },
            { "age_well_instruction", "AgeWell Instructions" },
            { "alarm_instruction", "Alarm Instruction Manual" },
            { "alarm_module_transmitter", "Alarm Transmitter Module" },
            { "ammo_display", "Ammo Display" },
            { "ancient_alien_relics", "\"Ancient Alien Relics\"" },
            { "animal_cage", "动物笼" },
            { "aquascan", "AquaScan" },
            { "armor_lining", "Kotton Lining" },
            { "aug_chip", "Augmentation Chip" },
            { "aug_id_guide", "改造体鉴别指南" },
            { "aug_scanner", "Aug Scanner" },
            { "back_inv_save_bag", "Back Inv Save Bag" },
            { "backpack_large", "Backpack (Large)" },
            { "backpack_large_military", "Large Military Backpack" },
            { "backpack_medium", "Backpack (Basic)" },
            { "backpack_medium_military", "Backpack (Army-Issue)" },
            { "backpack_small", "Backpack (Small)" },
            { "bandage", "Basic Bandage" },
            { "bandage_item", "基础绷带" },
            { "barrel", "Attachable Extended Barrel" },
            { "beerCase", "Red Imp Beer Case" },
            { "bipod", "Bipod" },
            { "birth_control_pill", "Birth Control Pill" },
            { "black_injector", "Synaprest Injector" },
            { "black_lamp", "Black Lamp" },
            { "blank_keycard", "Disposable Keycard (Blank)" },
            { "blank_module", "Blank Module" },
            { "blender", "Blender" },
            { "blood_bag", "Blood Bag" },
            { "bloomberry_seed", "Bloomberry Seed" },
            { "blue_blood_bag", "Bag of \"Blue Blood\"" },
            { "bottle_hot_sauce", "Hot Sauce" },
            { "bottle_printer", "Bottle Printer" },
            { "bottled_water", "Bottle of Water (Standard)" },
            { "bottled_water_premium", "Bottle of Spring Water" },
            { "box_cutter", "Box Cutter" },
            { "box_dispenser", "Box Dispenser" },
            { "box_tampon", "Box of PAX Tampons" },
            { "business_permit", "Business Permit" },
            { "c4", "Plastic Explosive" },
            { "c4_set", "Plastic Explosive (Armed)" },
            { "caffeine_pill", "Caffeine Pill" },
            { "canister_mbs", "MBS Nerve Gas" },
            { "card_brewer", "Business Card (Red Imp Brewery)" },
            { "card_chem", "Business Card (Chemist)" },
            { "card_mining", "Business Card (GP Mining Coop)" },
            { "card_pharma", "Business Card (Pharmacist)" },
            { "card_rev", "Business Card (Green)" },
            { "cassette1", "音乐磁带 - 毅力 （完好）" },
            { "cassette1d", "音乐磁带 - 毅力 （损坏）" },
            { "cassette1l", "音乐磁带 - 毅力 （受损）" },
            { "cassette2", "音乐磁带 - 数据领域 （完好）" },
            { "cassette2d", "音乐磁带 - 数据领域 （损坏）" },
            { "cassette2l", "音乐磁带 - 数据领域 （受损）" },
            { "cassette3", "音乐磁带 - 高风险 （完好）" },
            { "cassette3d", "音乐磁带 - 高风险 （损坏）" },
            { "cassette3l", "音乐磁带 - 高风险 （受损）" },
            { "cassette4", "音乐磁带 - 星尘 （完好）" },
            { "cassette4d", "音乐磁带 - 星尘 （损坏）" },
            { "cassette4l", "音乐磁带 - 星尘 （受损）" },
            { "cassette5", "音乐磁带 - 余晖 （完好）" },
            { "cassette5d", "音乐磁带 - 余晖 （损坏）" },
            { "cassette5l", "音乐磁带 - 余晖 （受损）" },
            { "cassette6", "音乐磁带 - 太空飞行 （完好）" },
            { "cassette6d", "音乐磁带 - 太空飞行 （损坏）" },
            { "cassette6l", "音乐磁带 - 太空飞行 （受损）" },
            { "cassette7", "音乐磁带 - 暗物质 （完好）" },
            { "cassette7d", "音乐磁带 - 暗物质 （损坏）" },
            { "cassette7l", "音乐磁带 - 暗物质 （受损）" },
            { "cassette_player", "Cassette Player" },
            { "cat_bar", "Cat Chocolate Bar" },
            { "cert1", "Appraisal Board Junior Certificate" },
            { "chem_finisher", "Chem Finisher" },
            { "chem_module", "Chemical Equipment Module" },
            { "chem_scanner", "Composition Spectrometer" },
            { "chemistry_guide", "Chemistry Manual" },
            { "cigarette_color", "Hemingway Color Checker" },
            { "cigarette_guide", "Hemingway Identification Guide" },
            { "cmd_keycard", "Disposable Keycard (Command)" },
            { "coffee_bean", "Coffee Beans" },
            { "combat_knife", "Combat Knife" },
            { "combat_machete", "Combat Machete" },
            { "common_chemical", "Chemical Supplies (Common)" },
            { "common_electronic", "Electronic Parts (Common)" },
            { "common_medical", "Medical Supplies (Common)" },
            { "common_ore", "Metal Ore" },
            { "compensator", "Compensator" },
            { "crowbar", "Crowbar" },
            { "crypto_module_cmd", "Cryptographic Desequencer Chip (Command)" },
            { "crypto_module_eng", "Cryptographic Desequencer Chip (Engineering)" },
            { "crypto_module_med", "Cryptographic Desequencer Chip (Medical)" },
            { "crypto_module_sec", "Cryptographic Desequencer Chip (Security)" },
            { "crypto_module_ser", "Cryptographic Desequencer Chip (Service)" },
            { "crypto_module_sup", "Cryptographic Desequencer Chip (Supply)" },
            { "cup_noodle", "Instant Ramen" },
            { "deed", "Deed" },
            { "dehydrated_water", "100% Pure Dehydrated Water" },
            { "desequencer", "Cryptographic Desequencer" },
            { "desequencer_instruction", "How To: The Desequencer" },
            { "dossier", "Dossier" },
            { "drain", "Water Drain" },
            { "dream_cap", "Dream Cap" },
            { "dream_cap_seed", "Dream Cap Spores" },
            { "dream_dust", "Vial of \"Dream Dust\"" },
            { "empty_beer_bottle", "Empty Beer Bottle" },
            { "energy_credit", "Energy Cell" },
            { "energy_credit_breeder", "Self Charging Energy Cell" },
            { "energy_credit_ext", "Energy Cell (Mk. II)" },
            { "energy_drink", "Energy Drink" },
            { "eng_box", "Engineering Foundry Supply Crate" },
            { "eng_keycard", "Disposable Keycard (Engineering)" },
            { "evaporator", "Evaporator" },
            { "evaporator_instruction", "Evaporator Instruction" },
            { "evaporator_module_solvent_recovery", "Evaporator Solvent Recovery Module" },
            { "evidence_box", "Security Department Evidence Locker" },
            { "exchange_directive", "Underground Exchange Directive" },
            { "expedition_box", "Expedition Supply Box" },
            { "expedition_log", "Expedition Log" },
            { "fanny_pack", "Fanny Pack" },
            { "fanta_pill", "Fanta Pill" },
            { "farm_module_dream_cap", "Dream Cap Neutralizer Hydroponic Module" },
            { "farm_module_fillerweed_production", "Fillerweed Production Hydroponic Module" },
            { "farm_module_hydroreed_filter", "Hydroreed Filter Hydroponic Module" },
            { "farm_module_kotton_loom", "Kotton Auto Loom Hydroponic Module" },
            { "farm_module_nightmare_cap", "Dream Cap Nightmare Hydroponic Module" },
            { "farm_module_nutrifruit", "Nutrifruit Hydroponic Module" },
            { "farm_module_smuggler", "Hydroponic Smuggler Module" },
            { "fat_meat", "Animal Fat" },
            { "faucet", "Water Faucet" },
            { "feces_large", "Animal Feces (Large)" },
            { "feces_medium", "Animal Feces" },
            { "feces_small", "Animal Feces (Small)" },
            { "fillerweed", "Fillerweed" },
            { "fillerweed_seed", "Fillerweed Seed" },
            { "flashbang_grenade", "Flashbang Grenade" },
            { "flashlight", "Flashlight" },
            { "flux_agent", "Flux Smelting Agent (Basic)" },
            { "food_stamp", "Food Stamp" },
            { "fuel_guide", "Plasma Cartridge Appraisal Guide" },
            { "furnace", "Furnace" },
            { "furnace_instruction", "How To: The Furnace" },
            { "furnace_module_blast", "Furnace Module (Blast)" },
            { "furnace_module_junk", "Furnace Module (Junk Processing)" },
            { "galaxy_blend", "Galaxy Blend" },
            { "gene_scanner", "基因扫描仪" },
            { "genetic_scanner", "Gene Scanner" },
            { "gl", "Underbarrel 25mm Grenade Launcher" },
            { "glass_shard", "Glass Shard" },
            { "glass_shard_shiv", "Glass Shiv" },
            { "glock_receiver", "Sentinel Mk. III." },
            { "grip", "Foregrip" },
            { "grip_gel", "Tactile Memory Grip Gel" },
            { "gun_part", "Gun Parts" },
            { "hand", "仿生机械手" },
            { "hand_guide", "仿生机械手鉴定指南" },
            { "handmade_pistol", "Nestfire Compact" },
            { "handnote", "Handnote" },
            { "hatchet", "Hatchet" },
            { "heating_plate", "Heating Plate" },
            { "heavy_handmade_pistol", "Ironcraft 10" },
            { "heavy_pistol_ammo", "10mm Ammunition" },
            { "heavy_pistol_ammo_nl", "10mm Ammunition (Non-Lethal)" },
            { "heavy_pistol_ammo_p", "10mm Ammunition (AP)" },
            { "hemostatic_bandage", "Hemostatic Bandage" },
            { "hemostatic_bandage_item", "止血绷带" },
            { "hidden_save_bag", "Hidden Save Bag" },
            { "husbandry_feces_large", "Animal Feces (Large)" },
            { "husbandry_feces_medium", "Animal Feces" },
            { "husbandry_feces_small", "Animal Feces (Small)" },
            { "husbandry_mouse_trap", "Mouse Trap" },
            { "husbandry_rat", "Rat" },
            { "husbandry_vacuum_robot", "Cleaner Robot" },
            { "hydroponic", "Hydroponic System" },
            { "hydroponic_guide", "Hydroponic Farming Manual" },
            { "hydroponic_instruction", "Hydroponic Instruction" },
            { "hydroponic_nutrient_tablet", "Hydroponic Nutrient Tablet" },
            { "hydroreed_filter", "Hydroreed Filter" },
            { "hydroreed_seed", "Hydroreed Seed" },
            { "ingot_book", "Metallurgy Manual" },
            { "injector_guide", "Immunivax Assessment Guide" },
            { "intel_sec", "Security Record" },
            { "internal_springs", "High Durability Internal Springs" },
            { "joe_card", "Business Card (Joe Wild)" },
            { "junk", "Junk" },
            { "kitchen_cleaver", "Meat Cleaver" },
            { "kitchen_knife", "Kitchen Knife" },
            { "kotton_fabric", "Kotton Fabric" },
            { "kotton_fiber", "Kotton Fiber" },
            { "kotton_seed", "Kotton Seed" },
            { "labeler", "Labeler" },
            { "labeler_blue", "Blue Labeler" },
            { "large_bottled_water", "Bottle of Water (Large)" },
            { "large_purple_injector", "Immunivax Injector" },
            { "laser", "Laser Sight" },
            { "laser2", "Target Acquisition Device" },
            { "laser_toy", "Toy Laser Pointer" },
            { "li_eat_snackbar", "Li-Eat Snack Bar" },
            { "livestock_feed_dispenser", "Livestock Feed Dispenser" },
            { "logo_checker", "Republic Logo Checker" },
            { "lottery_info", "Lower Levels Lottery Information" },
            { "lottery_ticket", "Lottery Ticket" },
            { "lottery_ticket_old", "Old Lottery Ticket" },
            { "machine_bay", "Machine Bay" },
            { "machine_bay_ext", "Machine Bay (Expanded)" },
            { "mag_10mm", "10mm Magazine" },
            { "mag_10mm_ext", "Extended 10mm Magazine" },
            { "mag_10mm_high", "High Capacity 10mm Magazine" },
            { "mag_10mm_smg", "10mm SMG Magazine" },
            { "mag_10mm_smg_box", "10mm SMG Box Magazine" },
            { "mag_10mm_smg_high", "10mm High Capacity SMG Magazine" },
            { "mag_22", ".22 Magazine" },
            { "mag_22_ext", "Extended .22 Magazine" },
            { "mag_22_high", "High Capacity .22 Magazine" },
            { "magnifier", "Magnifying Glass" },
            { "makeshift_storage_bay", "Makeshift Storage Bay" },
            { "match_barrel", "Match Grade Barrel" },
            { "meal_cap", "Meal Cap" },
            { "meat_scrap", "Offal" },
            { "med_bottle_blue", "Bottle of Basic Solution" },
            { "med_bottle_orange", "Bottle of Reducing Agent" },
            { "med_bottle_red", "Bottle of Acidic Solution" },
            { "med_bottle_small_pink", "Bottle of Lipobond Agent" },
            { "med_bottle_violet", "Bottle of N-Methylol Base" },
            { "med_box", "Medical Bay Supply Crate" },
            { "med_keycard", "Disposable Keycard (Medical)" },
            { "mentor_contract", "Lease Agreement" },
            { "metal_ingot", "Metal Ingot" },
            { "metal_scanner", "Scav Scanner" },
            { "mini_bottle", "Bottle of Water (Micro)" },
            { "mirage_projector", "Mirage Projector" },
            { "modified_access_card", "Modified Access Card" },
            { "module_bay_expansion_kit", "Module Bay Expansion Kit" },
            { "module_extractor", "Module Extractor (Basic)" },
            { "module_extractor_advanced", "Module Extractor (Advanced)" },
            { "moisture_farm", "Moisture Farm" },
            { "moisture_farm_instruction", "How To: The Moisture Farm" },
            { "morsel", "Morsel" },
            { "mouse_trap", "Mouse Trap" },
            { "neuroactive_perfume", "SYNC Neuroactive Perfume" },
            { "newspaper", "Newspaper" },
            { "nightmare_cap", "Nightmare Cap" },
            { "nightmare_dust", "Vial of \"Nightmare Dust\"" },
            { "node_medium", "Node (Medium)" },
            { "node_small", "Node (Small)" },
            { "nuclear_waste", "Radioactive Waste" },
            { "nudka", "Nudka" },
            { "nutrient_tablet", "水培营养片" },
            { "nutrient_tablet_container", "Hydroponic Nutrient Tablet Bottle" },
            { "nutrifruit", "Nutrifruit" },
            { "nutrifruit_seed", "Nutrifruit Seed" },
            { "nutrifruit_seed_packet", "Packet of Nutrifruit Seeds" },
            { "nuts_metal", "Metal Screws" },
            { "pack_condom", "Box of REX Condoms" },
            { "packet_red_cigarette", "Pack of Hemingway Cigarettes" },
            { "paper_towel", "Roll of Paper Towels" },
            { "permit_gun_1", "Class 1 Weapon Permit" },
            { "permit_gun_2", "Class 2 Weapon Permit" },
            { "permit_gun_3", "Class 3 Weapon Permit" },
            { "phagimycin_pill", "Phagimycin Pill" },
            { "pheromone_perfume", "L'ESSENCE Pheromone Perfume" },
            { "pink_alt_injector", "Nomore Injector" },
            { "pink_injector", "Oxymore Injector" },
            { "pipe_weapon", "Lead Pipe" },
            { "pistol_switch", "Pistol Auto Sear" },
            { "plant_analyser", "Plant Analyser" },
            { "plasma_fuel", "Plasma Cartridge" },
            { "plastic_bag", "bag" },
            { "portable_water_purifier", "HydraTech Micro Water Purifier" },
            { "postit", "Postit" },
            { "powerblock", "PowerBloc" },
            { "printed_gun", "Liberator 3D Printed Pistol" },
            { "printer", "3D Printer" },
            { "printer_chip_10_mag", "3D Printer Chip (x{0} 10MM Magazine)" },
            { "printer_chip_10_mag_ext", "3D Printer Chip (x{0} Ext. 10MM Mag.)" },
            { "printer_chip_10_mag_high", "3D Printer Chip (x{0} High Cap. 10MM Mag.)" },
            { "printer_chip_22_mag", "3D Printer Chip (x{0} .22 Magazine)" },
            { "printer_chip_22_mag_ext", "3D Printer Chip (x{0} Ext. .22 Mag.)" },
            { "printer_chip_22_mag_high", "3D Printer Chip (x{0} High Cap. .22 Mag.)" },
            { "printer_chip_laser_sight", "3D Printer Chip (x{0} Laser Sight)" },
            { "printer_chip_makeshift_rds", "3D Printer Chip (x{0} Makeshift RDS)" },
            { "printer_chip_makeshift_toy_laser", "3D Printer Chip (x{0} Toy Laser Pointer)" },
            { "printer_chip_pistol", ".22 Pistol 3D Printer Chip" },
            { "printer_chip_rds", "3D Printer Chip (x{0} RDS)" },
            { "printer_chip_silencer", "3D Printer Chip (x{0} Silencer)" },
            { "printer_chip_small_bottle", "3D Printer Chip (x{0} Small Plastic Bottle)" },
            { "printer_module_metal", "Metal Printer Module" },
            { "printer_plastic", "3D Printing Filament" },
            { "processed_cheese", "Processed Cheese" },
            { "processed_juice", "Puice" },
            { "processed_meat", "Peat" },
            { "processed_milk", "Pilk" },
            { "procurement_slip", "Procurement Slip" },
            { "projector_instruction", "How To: The Projector" },
            { "pure_white_injector", "Naloxgone Injector" },
            { "rare_electronic", "Electronic Parts (Rare)" },
            { "rare_ore", "Rare Metal Ore" },
            { "rat", "Rat" },
            { "raw_meat", "Raw Meat (Standard)" },
            { "rds", "Red Dot Sight" },
            { "rds_makeshift", "Makeshift Red Dot Sight" },
            { "recharger", "Recharger" },
            { "red_beer", "Red Imp Beer" },
            { "restricted_chemical", "Chemical Supplies (Restricted)" },
            { "restricted_medical", "Medical Supplies (Restricted)" },
            { "rev_codeword", "暗号清单" },
            { "revolver", "Lancewell Revolver" },
            { "ribwich", "Packaged Rib Sandwich" },
            { "ribwich_guide", "Ribwich Appraisal Guide" },
            { "rubbing_alcohol", "Rubbing Alcohol" },
            { "salve", "Nightingale's Salve" },
            { "satchel", "Satchel (Small)" },
            { "save_bag", "Save Bag" },
            { "scav_journal", "Scav's journal entry" },
            { "scav_token", "Scavenger's Token" },
            { "sci_box", "Research Department Supply Crate" },
            { "sci_keycard", "Disposable Keycard (Research)" },
            { "scrap_metal", "Scrap Metal" },
            { "scratcher", "Scratcher Ticket" },
            { "scratcher_stack", "Stack of Scratcher Tickets (5)" },
            { "screwdriver", "Screwdriver" },
            { "sec_box", "Security Department Supply Crate" },
            { "sec_keycard", "Disposable Keycard (Security)" },
            { "sec_slip", "Incident Slip" },
            { "security_alarm", "Alarm System" },
            { "ser_keycard", "Disposable Keycard (Service)" },
            { "serum_green", "牲畜免疫血清" },
            { "serum_red", "牲畜类固醇血清" },
            { "service_box", "Service Department Supply Crate" },
            { "shampoo", "Bottle of 4 In 1 Wash" },
            { "short_stock", "Buckler Stock" },
            { "shotgun", "Rampart Dual-Action Shotgun" },
            { "showcase_save_bag", "Hidden Save Bag" },
            { "sign_expedition", "Expedition Sign" },
            { "sign_food", "Food Neon Sign" },
            { "sign_household", "Household Item Neon Sign" },
            { "sign_luxury", "Luxury Item Neon Sign" },
            { "sign_material", "Material Neon Sign" },
            { "sign_medical", "Medical Neon Sign" },
            { "sign_water", "Water Neon Sign" },
            { "silencer", "Suppressor" },
            { "silencer2", "Night Owl Suppressor" },
            { "silencer_makeshift", "Makeshift Suppressor" },
            { "skincare_cream", "ETERNAL Rejuvenation Serum" },
            { "skinning_knife", "Skinning Knife" },
            { "slip", "Slip" },
            { "small_bottled_water", "Bottle of Water (Small)" },
            { "small_morsel", "Small Morsel" },
            { "small_pistol_ammo", ".22 SR Ammunition" },
            { "small_pistol_ammo_nl", ".22 SR Ammunition (Non-Lethal)" },
            { "small_pistol_ammo_p", ".22 SR Ammunition (AP)" },
            { "small_raw_meat", "Raw Meat (Small)" },
            { "smelling_salt", "Smelling Salts" },
            { "smg", "Peacemaker Heavy SMG" },
            { "smoke_grenade", "Smoke Grenade" },
            { "smuggler_bay", "Smuggler's Bay" },
            { "smuggler_bay_mini", "Mini Smuggler's Bay" },
            { "smuggler_bay_mod", "Smuggler's Bay (Modified)" },
            { "soda_red", "Soda" },
            { "sold_save_bag", "Hidden Save Bag" },
            { "stamp_guide", "Food Stamp Identification Handbook" },
            { "stock", "Guardian Stock" },
            { "storage_bay", "Storage Bay" },
            { "storage_bay_chem", "Chemist Storage Bay" },
            { "storage_bay_gun", "Gunsmith Storage Bay" },
            { "storage_bay_large", "Storage Bay (Extended)" },
            { "stun_baton", "Stun Baton" },
            { "stun_gun", "PulseGuard Stun Gun" },
            { "sup_box", "Supply Department Supply Crate" },
            { "sup_keycard", "Disposable Keycard (Supply)" },
            { "surgery_tool", "Surgery Toolset" },
            { "system_capped_neural_core", "Neural Core Module (Capped)" },
            { "system_module_corrupt", "Corrupted Module" },
            { "system_module_eco", "Eco Module" },
            { "system_module_efficiancy", "Efficiency Module" },
            { "system_module_fineness", "Refinement Module" },
            { "system_module_overclock", "Overclock Module" },
            { "system_module_performance", "Performance Module" },
            { "system_module_quality", "Quality Module" },
            { "system_module_ruined", "Ruined Module" },
            { "system_module_streamlining", "Streamlining Module" },
            { "system_uncapped_neural_core", "Neural Core Module (Uncapped)" },
            { "tazer", "Tazer" },
            { "test_gizmo", "Test Gizmo" },
            { "toilet_paper", "Roll of Toilet Paper" },
            { "toolbox", "Toolbox" },
            { "toothpaste", "Tube of Toothpaste" },
            { "topical_bandage", "Topical Medication Bandage" },
            { "topical_bandage_item", "外用药膏绷带" },
            { "trashcan", "Trash Can" },
            { "trigger_group", "Tuned Trigger Group" },
            { "turbo_booster", "Disposable Turbo Booster" },
            { "turbo_booster_adv", "Advanced Turbo Booster" },
            { "tutorial_book", "Mentor's Handbook" },
            { "tutorial_page", "Title" },
            { "unlicensed_phagimycin_pill", "Unlicensed Phagimycin Pill" },
            { "used_water_testing_strip", "Water Testing Strip (Used)" },
            { "uv_filter", "UV Lamp" },
            { "vacuum_robot", "Cleaner Robot" },
            { "vending_fountain", "Vending Fountain" },
            { "vending_fountain_core", "Vending Fountain Core" },
            { "vending_machine", "Vending Machine" },
            { "vending_machine_core", "Vending Machine Core" },
            { "wanted_paper", "Security Wanted List" },
            { "water_filter", "Water Filter" },
            { "water_filter_adv", "Advanced Water Filter" },
            { "water_guide", "Water Trading Manual" },
            { "water_jug", "Jug of Water" },
            { "water_pitcher", "Water Pitcher" },
            { "water_purifier", "Water Purifier" },
            { "water_purifier_instruction", "Water Purifier Instructions" },
            { "water_ration", "Sealed Water Ration (Standard)" },
            { "water_ration_small", "Sealed Water Ration (Small)" },
            { "water_tablet", "Water Purification Tablet" },
            { "water_tablet_container", "Bottle of Water Purification Tablets" },
            { "water_test_container", "Water Testing Kit" },
            { "water_test_strip", "Water Testing Strip" },
            { "welder", "Plasma Cutter" },
            { "wine_berry", "BloomBerry" },
            { "wine_bloomberry", "BloomBerry Wine" },
            { "wine_book", "BloomBerry Wine Fermenting Guide" },
            { "wine_bottle", "Wine Bottle" },
            { "wine_gloomberry", "GloomBerry Wine" },
            { "wine_rack", "催陈器" },
            { "wine_superyeast", "Super Yeast" },
            { "wine_yeast", "Yeast" },
            { "wine_yeast_infinite", "Yeast Bioreactor" },
            { "wine_yeast_red", "Synthetic Yeast" },
            { "wire", "Wire" },
            { "wire_cutter", "Wire Cutter" },
            { "xray_scanner", "Portable XRay Scanner" },
            { "zerochew", "ZeroChew Tab" },
            { "zyanide_pill", "Zyanide Pill" },
        };

        /// <summary>英文名。查不到返回 null（调用方自己回落）。</summary>
        public static string En(string id)
        {
            if (string.IsNullOrEmpty(id)) return null;
            string v;
            return Map.TryGetValue(id, out v) ? v : null;
        }
    }
}
